# Generated by Django 3.2.16 on 2022-10-13 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_garden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden_tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('descreption', models.TextField()),
                ('tips_date', models.DateField(verbose_name=datetime.datetime(2022, 10, 13, 10, 44, 21, 431235))),
            ],
        ),
    ]
