# Generated by Django 3.2.16 on 2022-10-13 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_garden_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden_tips',
            name='tips_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 10, 13, 10, 56, 15, 116456)),
        ),
    ]
